package dkit.oop;

public enum AdminMenu
{
    QUIT_APPLICATION,
    ADD_COURSE,
    REMOVE_COURSE,
    DISPLAY_ALL_COURSES,
    COURSE_DETAILS,
    ADD_STUDENT,
    REMOVE_STUDENT,
    DISPLAY_STUDENT,
    SAVE_AND_EXIT;
}
